[package]
name = "cn"
version = "2.0.0"
authors = ["Arijit Dey <arijid79@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
ansi_term = "0.11.0"
atty = "0.2.14"
async-recursion = "0.3.1"
futures = "0.3.7"
async-std = { version = "1.7.0", features = ["attributes"]}